name: fishlog
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.10
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  geolocator: ^14.0.2
  image_picker: ^1.2.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.3+1
  google_maps_flutter: ^2.14.0
  http: ^1.6.0
  path_provider: ^2.1.3
  path: ^1.9.0
  geocoding: ^4.0.0
  provider: ^6.1.2
  bcrypt: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  analyzer: ^6.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/icon/icon.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#003366"
  image: "assets/icon/icon.png"
  android: true
  ios: false
  web: false